### ISSUE TITLE
Destination array was not long enough

### ISSUE THREAD

**Issue by molinch** [molinch/FFImageLoading#69] opened 2015-11-18 17:29 UTC
This happened today:

<pre>
Nov 18 18:26:55 iPad-de-Fabien eCatTouch[2699] <Warning>:
Unhandled Exception:
System.ArgumentException: Destination array was not long enough. Check destIndex and length, and the array's lower bounds
at System.Array.Copy (System.Array sourceArray, Int32 sourceIndex, System.Array destinationArray, Int32 destinationIndex, Int32 length) <0x100408650 + 0x003ac> in <filename unknown>:0
at System.Collections.Generic.List`1[T].CopyTo (System.Collections.Generic.T[] array, Int32 arrayIndex) <0x100213d94 + 0x00033> in <filename unknown>:0
at System.Collections.Generic.List`1[T]..ctor (IEnumerable`1 collection) <0x1002130a8 + 0x000e7> in <filename unknown>:0
at System.Linq.Enumerable.ToList[TSource] (IEnumerable`1 source) <0x10077a1d0 + 0x00047> in <filename unknown>:0
at FFImageLoading.Work.WorkScheduler+<LoadImage>c__async0.MoveNext () <0x100fe7f40 + 0x00157> in <filename unknown>:0
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>m__0 (System.Object state) <0x10027e784 + 0x00050> in <filename unknown>:0
at UIKit.UIKitSynchronizationContext+<Post>c__AnonStorey0.<>m__0 () <0x10013d6e4 + 0x0001b> in <filename unknown>:0
at Foundation.NSAsyncActionDispatcher.Apply () <0x100150600 + 0x00023> in <filename unknown>:0
at (wrapper managed-to-native) UIKit.UIApplication:UIApplicationMain (int,string[],intptr,intptr)
at UIKit.UIApplication.Main (System.String[] args, System.String principalClassName, System.String delegateClassName) <0x1001373c8 + 0x0009b> in <filename unknown>:0
at eCat.Touch.Application.Main (System.String[] args) <0x10009d230 + 0x0001b> in <filename unknown>:0
</pre>

**Comment by daniel-luberda** [comment] 2015-12-04 12:42
I think it may be caused by this: https://github.com/molinch/FFImageLoading/blob/master/source/FFImageLoading.Common/Work/WorkScheduler.cs#L239-L242
```
lock (_pauseWorkLock)
{
	_pendingTasks.Add(currentPendingTask);
}
```

It's missing `lock (_pendingTasksLock)` as everywhere else where `_pendingTasks` is modified.

**Comment by daniel-luberda** [comment] 2015-12-08 18:26
I fixed it in: https://github.com/molinch/FFImageLoading/commit/13895f05c2a52c604ef7f360f84d9e0ae2b259cb

**Comment by molinch** [comment] 2015-12-11 07:43
Could be fixed. So far I haven't got it again in production (we are using older sources that don't contain the fix).

**Comment by daniel-luberda** [comment] 2015-12-11 09:58
Ok, so maybe we can close it? I haven't got it either.

**Closed** 2015-12-14 14:04 UTC
