### ISSUE TITLE
Error applying Android Transform to image

### ISSUE THREAD

**Issue by goneale** [molinch/FFImageLoading#82] opened 2015-12-02 04:06 UTC
With this code inside `override void OnBindViewHolder(RecyclerView.ViewHolder viewHolder, int position)` of a `RecyclerView.Adapter`:
```
ImageService.LoadUrl(item.ImageUrl)
               .Retry(3, 200)
               .DownSample(1080)
               .Transform(new BlurredTransformation(24f))
               .Into(vh.Image);
```

When I press the back button in my Android Toolbar or even intermittently on load, I receive the following exception which crashes the app soon after displaying the blurred effect:

```
12-01 22:36:21.497 E/mono-rt (24120): [ERROR] FATAL UNHANDLED EXCEPTION: Java.Lang.RuntimeException: Canvas: trying to use a recycled bitmap android.graphics.Bitmap@529be970
12-01 22:36:21.497 E/mono-rt (24120):   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in /Users/builder/data/lanes/2098/3efa14c4/source/mono/external/referencesource/mscorlib/system/runtime/exceptionservices/exceptionservicescommon.cs:143 
12-01 22:36:21.497 E/mono-rt (24120):   at Android.Runtime.JNIEnv.CallNonvirtualVoidMethod (IntPtr jobject, IntPtr jclass, IntPtr jmethod, Android.Runtime.JValue* parms) [0x00084] in /Users/builder/data/lanes/2098/3efa14c4/source/monodroid/src/Mono.Android/src/Runtime/JNIEnv.g.cs:1029 
12-01 22:36:21.497 E/mono-rt (24120):   at Android.Graphics.Drawables.BitmapDrawable.Draw (Android.Graphics.Canvas canvas) [0x00070] in /Users/builder/data/lanes/2098/3efa14c4/source/monodroid/src/Mono.Android/platforms/android-23/src/generated/Android.Graphics.Drawables.BitmapDrawable.cs:619 
12-01 22:36:21.497 E/mono-rt (24120):   at FFImageLoading.Work.FFBitmapDrawable.Draw (Android.Graphics.Canvas canvas) [0x00019] in <filename unknown>:0 
12-01 22:36:21.497 E/mono-rt (24120):   at Android.Graphics.Drawables.BitmapDrawable.n_Draw_Landroid_graphics_Canvas_ (IntPtr jnienv, IntPtr native__this, IntPtr native_canvas) [0x00011] in /Users/builder/data/lanes/2098/3efa14c4/source/monodroid/src/Mono.Android/platforms/android-23/src/generated/Android.Graphics.Drawables.BitmapDrawable.cs:601 
12-01 22:36:21.497 E/mono-rt (24120):   at (wrapper dynamic-method) System.Object:b8009a04-c092-4fa4-ae64-cc34b063b436 (intptr,intptr,intptr)
12-01 22:36:21.497 E/mono-rt (24120):   --- End of managed exception stack trace ---
12-01 22:36:21.497 E/mono-rt (24120): java.lang.RuntimeException: Canvas: trying to use a recycled bitmap android.graphics.Bitmap@529be970
12-01 22:36:21.497 E/mono-rt (24120): 	at android.graphics.Canvas.throwIfCannotDraw(Canvas.java:1084)
12-01 22:36:21.497 E/mono-rt (24120): 	at android.view.GLES20Canvas.drawBitmap(GLES20Canvas.java:844)
12-01 22:36:21.497 E/mono-rt (24120): 	at android.graphics.drawable.BitmapDrawable.draw(BitmapDrawable.java:490)
12-01 22:36:21.497 E/mono-rt (24120): 	at md564c4a2b9f24024bbfe8a5a73e9baebd9.FFBitmapDrawable.n_draw(Native Method)
12-01 22:36:21.497 E/mono-rt (24120): 	at md564c4a2b9f24024bbfe8a5a73e9baebd9.FFBitmapDrawable.draw(FFBitmapDrawable.java:94)
12-01 22:36:21.497 E/mono-rt (24120): 	at android.widget.ImageView.onDraw(ImageView.java:1037)
12-01 22:36:21.497 E/mono-rt (24120): 	at android.view.View.draw(View.java:14465)
12-01 22:36:21.497 E/mono-rt (24120): 	at android.view.View.getDisplayList(View.java:13362)
12-01 22:36:21.497 E/mono-rt (24120): 	at android.view.View.getDisplayList(View.java:13404)
12-01 22:36:21.497 E/mono-rt (24120): 	at android.view.View.draw(View.java:14182)
12-01 22:36:21.497 E/mono-rt (24120): 	at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
12-01 22:36:21.497 E/mono-rt (24120): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
12-01 22:36:21.497 E/mono-rt (24120): 	at android.view.View.draw(View.java:14468)
12-01 22:36:21.497 E/mono-rt (24120): 	at android.view.View.getDisplayList(View.java:13362)
12-01 22:36:21.497 E/mono-rt (24120): 	at android.view.View.getDisplayList(View.java:13404)
12-01 22:36:21.497 E/mono-rt (24120): 	at android.view.View.draw(View.java:14182)
12-01 22:36:21.497 E/mono-rt (24120): 	at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
12-01 22:36:21.497 E/mono-rt (24120): 	at android.support.v7.widget.RecyclerView.drawChild(RecyclerView.java:3693)
12-01 22:36:21.497 E/mono-rt (24120): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
12-01 22:36:21.497 E/mono-rt (24120): 	at android.view.View.draw(View.java:14468)
12-01 22:36:21.497 E/mono-rt (24120): 	at android.support.v7.widget.RecyclerView.draw(RecyclerView.java:3171)
12-01 22:36:21.497 E/mono-rt (24120): 	at android.view.View.getDisplayList(View.java:13362)
12-01 22:36:21.497 E/mono-rt (24120): 	at android.view.View.getDisplayList(View.java:13404)
12-01 22:36:21.497 E/mono-rt (24120): 	at android.view.View.draw(View.java:14182)
12-01 22:36:21.497 E/mono-rt (24120): 	at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
12-01 22:36:21.497 E/mono-rt (24120): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
12-01 22:36:21.497 E/mono-rt (24120): 	at android.view.View.getDisplayList(View.java:13357)
12-01 22:36:21.497 E/mono-rt (24120): 	at android.view.View.getDisplayList(View.java:13404)
12-01 22:36:21.497 E/mono-rt (24120): 	at android.view.View.draw(View.java:14182)
12-01 22:36:21.497 E/mono-rt (24120): 	at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
12-01 22:36:21.497 E/mono-rt (24120): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
12-01 22:36:21.497 E/mono-rt (24120): 	at android.view.View.getDisplayList(View.java:13357)
12-01 22:36:21.497 E/mono-rt (24120): 	at android.view.View.getDisplayList(View.java:13404)
12-01 22:36:21.497 E/mono-rt (24120): 	at android.view.View.draw(View.java:14182)
12-01 22:36:21.497 E/mono-rt (24120): 	at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
12-01 22:36:21.497 E/mono-rt (24120): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
12-01 22:36:21.497 E/mono-rt (24120): 	at android.view.View.getDisplayList(View.java:13357)
12-01 22:36:21.497 E/mono-rt (24120): 	at android.view.View.getDisplayList(View.java:13404)
12-01 22:36:21.497 E/mono-rt (24120): 	at android.view.View.draw(View.java:14182)
12-01 22:36:21.497 E/mono-rt (24120): 	at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
12-01 22:36:21.497 E/mono-rt (24120): 	at android.support.v4.widget.DrawerLayout.drawChild(DrawerLayout.java:1229)
12-01 22:36:21.497 E/mono-rt (24120): 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
12-01 22:36:21.497 E/mono-rt (24120): 	at android.view.View.getDisplayList(View.java:13357)
12-01 22:36:21.497 E/mono-rt (24120): 	at android.view.View.getDisplayList(View.java:1
```

**Comment by molinch** [comment] 2015-12-02 11:46
If you know some exact steps that lead to that. Could you write them?

**Comment by molinch** [comment] 2015-12-02 21:10
Btw I tried to repro this exact issue during 1h and didn't managed to have it.
If you can detail as much as possible that's gonna help for debugging.
Thanks

**Comment by goneale** [comment] 2015-12-02 23:08
Try swapping out Universal Image Loader for FFImageLoading in this sample, that is the Xamarin template I started with. I do believe it's an issue in conjunction with recycler views. https://github.com/jamesmontemagno/Xam.NavDrawer

**Comment by molinch** [comment] 2015-12-03 07:14
Which Android version?

**Comment by goneale** [comment] 2015-12-03 22:07
4.4.4

**Comment by ahohns** [comment] 2015-12-04 05:43
Have also received this error. Android 6, Xamarin Forms 1.5.1.6471, FFImageLoading 2.0.0-alpha1
```
[Bitmap] Called hasAlpha() on a recycle()'d bitmap! This is undefined behavior!
[MonoDroid] UNHANDLED EXCEPTION:
[MonoDroid] Java.Lang.RuntimeException: Exception of type 'Java.Lang.RuntimeException' was thrown.
[MonoDroid] at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () <0x00028>
[MonoDroid] at Android.Runtime.JNIEnv.CallNonvirtualVoidMethod (intptr,intptr,intptr,Android.Runtime.JValue*) <0x000e7>
[MonoDroid] at Android.Graphics.Drawables.BitmapDrawable.Draw (Android.Graphics.Canvas) <0x001cb>
[MonoDroid] at FFImageLoading.Work.FFBitmapDrawable.Draw (Android.Graphics.Canvas) <0x00033>
[MonoDroid] at Android.Graphics.Drawables.BitmapDrawable.n_Draw_Landroid_graphics_Canvas_ (intptr,intptr,intptr) <0x0005b>
[MonoDroid] at (wrapper dynamic-method) object.5fb8ea0e-2829-401d-a1cb-cc397f174bf7 (intptr,intptr,intptr) <0x00043>
[MonoDroid]   --- End of managed exception stack trace ---
[MonoDroid] java.lang.RuntimeException: Canvas: trying to use a recycled bitmap android.graphics.Bitmap@d0b1e9e
```

**Comment by daniel-luberda** [comment] 2015-12-04 06:01
@ahohns Can you give me some code to reproduce Xamarin.Forms bug? I'll Debug it. Do you use transformations?

**Comment by ahohns** [comment] 2015-12-04 06:10
I can't at the moment sorry, as I only just noticed it for the first time this afternoon testing a new beta release. Yep using a custom transformation.

While we're only on XF 1.5.1 we're using TwinTechs FastCell in a ListView which uses recycling.

**Comment by daniel-luberda** [comment] 2015-12-04 06:11
@ahohns If you're using a custom transformations be sure not to dispose/recycle source bitmap. It's really important as FFImageLoading does it after transformation. I'm quite sure it's the cause.

**Comment by ahohns** [comment] 2015-12-04 06:25
Hmm I don't believe we're doing anything with the source, it's a simple transformation to create a circle image with a border which pretty much follows existing transformations:

```
protected override Bitmap Transform (Bitmap source)
		{
			double size = source.Width >= _width ? source.Width : _width * App.ScreenScale;

			float rad = (float)(Math.Min(size, size) / 2);

			Bitmap output = Bitmap.CreateBitmap((int)size, (int)size, Bitmap.Config.Argb8888);
			using (Canvas canvas = new Canvas(output))
			using (Paint paint = new Paint ())
			using (BitmapShader shader = new BitmapShader (source, Shader.TileMode.Clamp, Shader.TileMode.Clamp))
			using (RectF rectF = new RectF(BorderThickness/2, BorderThickness/2, (int)size - BorderThickness/2, (int)size - BorderThickness/2))
			{
				paint.AntiAlias = true;
				paint.SetShader (shader);

				canvas.DrawRoundRect (rectF, rad, rad, paint);

				if (BorderThickness > 0) {
					paint.Color = BorderColor.ToAndroid ();
					paint.SetStyle (Paint.Style.Stroke);
					paint.StrokeWidth = BorderThickness;
					paint.SetShader (null);
					canvas.DrawRoundRect (rectF, rad, rad, paint);
				}

				return output;				
			}
		}
```

**Comment by daniel-luberda** [comment] 2015-12-04 06:43
I just tested it on a large list and couldn't reproduce it. Your transformations works without any exception.

**Comment by molinch** [comment] 2015-12-04 06:54
Did you guys got it in simulator too?
If yes could you tell me your config? (So I can match it)

**Comment by molinch** [comment] 2015-12-11 07:38
@ahohns @goneale Could you give more info? Do you still have the issue btw?
If you have a repro sample would it be OK to share it? (can be done by email for privacy reasons)

**Comment by ahohns** [comment] 2015-12-11 07:47
I was able to almost always repro it this morning (using alpha-5) but another exception was happening around the same time and once I fixed that I didn't have a way to repro it any more. Perhaps it was the way we were doing something and changing it fixed it. We're using Xamarin Insights with our testers so if I see the issue still happening we'll try and track it down again.

**Comment by ahohns** [comment] 2015-12-14 06:50
@molinch @daniel-luberda Did some testing using alpha-6 on a slow device today and finally got this error again. Unfortunately it was totally random, but it's possible there's some sort of corruption going on and looking at Xamarin Insights the devices we see this error from are slower / older devices. We're using Xamarin 1.5.1

In rare cases after clicking around the app really fast (especially different pages that load heaps of images) we'll go back to the root page and there will be random images appearing in the wrong place almost as if the wrong images are being loaded back in the wrong place. This is what happened today when I received the error .. our root page has a background image that's a CachedImage loaded from ImageSource.File and it never changes, but when returning back from another page the background image had changed to an image that's dynamically loaded (ImageSource.FromUri) and the place where the dynamically loaded image was from was now blank. A few seconds later is when the app crashed.

Hard to explain and unfortunately unable to reliably reproduce other than click around like mad, but there's definitely something strange happening. We're under a deadline here so I can't put much time into it, but after that I can try and help hunt it down.

I don't suppose the error could at least be caught in FFBitmapDrawable.Draw() so it doesn't cause a fatal exception?

**Comment by molinch** [comment] 2015-12-14 07:17
Many thanks for investigating it @ahohns 
On Android bitmap memory is not reclaimed in a deterministic way.
Due to that memory will grow until GC kicks in. Currently we force GC only when getting an OutOfMemoryException, which oftently only delays the issue.
Therefore when the memory is really too low Android kills the app and there is no way to catch it. I believe that is what happens here. I could be wrong but I don't think this is catchable.

The best would be to profile the app to see if there are memory leaks due to the app, or due to ImageLoading, or even due to Xamarin.

**Comment by ahohns** [comment] 2015-12-15 01:13
A bit of googling and the impression I get is the error is thrown when trying to use a bitmap that has been recycled or collected, either manually or when imageView is recycling the drawing cache for whatever reason. So perhaps it is somewhat memory related where a bitmap gets thrown out of the cache but is still being referenced somehow? 
The app itself is never in danger of running out of memory according to profiling.

I can more reliably trigger this during testing this morning. I need to browse around the app having lots of images being loaded, then I press the home button to minimise the app and put it to sleep. I then open the app back up via the app switcher (the square button heh, don't know the proper name!) and that's when the crash happens for me. Perhaps it's android freeing up memory and the image cache getting destroyed?

**Comment by molinch** [comment] 2015-12-16 12:43
It's not on Nuget so far but there is a branch with changes that will definitely help: https://github.com/molinch/FFImageLoading/tree/better-bitmap-pool

Could you give it a try? @goneale @ahohns

**Comment by daniel-luberda** [comment] 2015-12-16 18:17
@molinch Tested it for a while and didn't experienced any problems yet. It works very good! The only problem is I still experience this: #91 which is definitely a cache bug (if I modify transformation key to return random string, so it bypasses cache, it works good)

**Comment by molinch** [comment] 2015-12-16 19:47
Ok that's great, on my side I didn't got any issue too but I tested it so far on a real projet.
I'll check for #91 now

**Comment by ahohns** [comment] 2015-12-16 23:50
@molinch Wow nice work, you're a ninja! I won't be able to test until Monday (Australian time) but will definitely give it a go then.

**Comment by daniel-luberda** [comment] 2015-12-17 00:10
@molinch @ahohns I'll make a nuget with recent changes (alpha8).

**Comment by ahohns** [comment] 2015-12-21 04:18
Seems good here so far - ran it through its paces same as last week and haven't had any issues. I did get one random "trying to use recycled bitmap" error but it didn't have any useful stacktrace this time (no FFImageLoading trace etc) so it might not have been from this library.

**Comment by daniel-luberda** [comment] 2015-12-21 13:31
@ahohns Thanks for the info. We could close it then. Feel free to reopen it if you experience those exceptions while testing.

**Closed by daniel-luberda** 2015-12-21 13:31 UTC

**Comment by softsan** [comment] 2017-06-28 17:29
It is happening with us on the android on ffimageloading nuget version 2.2.9

[Bitmap] Called hasAlpha() on a recycle()'d bitmap! This is undefined behavior!
[Bitmap] Called hasAlpha() on a recycle()'d bitmap! This is undefined behavior!
[Bitmap] Called hasAlpha() on a recycle()'d bitmap! This is undefined behavior!
[Choreographer] Skipped 137 frames!  The application may be doing too much work on its main thread.
[Bitmap] Called hasAlpha() on a recycle()'d bitmap! This is undefined behavior!
[Bitmap] Called hasAlpha() on a recycle()'d bitmap! This is undefined behavior!
[Bitmap] Called hasAlpha() on a recycle()'d bitmap! This is undefined behavior!
[Bitmap] Called hasAlpha() on a recycle()'d bitmap! This is undefined behavior!
[Bitmap] Called hasAlpha() on a recycle()'d bitmap! This is undefined behavior!
[Bitmap] Called hasAlpha() on a recycle()'d bitmap! This is undefined behavior!

[MonoDroid] UNHANDLED EXCEPTION:
[MonoDroid] Java.Lang.RuntimeException: Canvas: trying to use a recycled bitmap android.graphics.Bitmap@cc0cabd
[MonoDroid]   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <3fd174ff54b146228c505f23cf75ce71>:0 
[MonoDroid]   at Java.Interop.JniEnvironment+InstanceMethods.CallNonvirtualVoidMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniObjectReference type, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x00089] in <bd30a18775d94dc8b6263aecd1ca9077>:0 
[MonoDroid]   at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeVirtualVoidMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x0005d] in <bd30a18775d94dc8b6263aecd1ca9077>:0 
[MonoDroid]   at Xamarin.Forms.Platform.Android.ScrollViewRenderer.Draw (Android.Graphics.Canvas canvas) [0x0000d] in C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Platform.Android\Renderers\ScrollViewRenderer.cs:99 
[MonoDroid]   at Android.Views.View.n_Draw_Landroid_graphics_Canvas_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_canvas) [0x0000f] in <9ab9faae1b4b4f0da28e7c4ac61e2c78>:0 
[MonoDroid]   at (wrapper dynamic-method) System.Object:c607ed46-a12d-466c-ad92-03e135cadf1e (intptr,intptr,intptr)
[MonoDroid]   --- End of managed Java.Lang.RuntimeException stack trace ---
[MonoDroid] java.lang.RuntimeException: Canvas: trying to use a recycled bitmap android.graphics.Bitmap@cc0cabd
[MonoDroid] 	at android.graphics.Canvas.throwIfCannotDraw(Canvas.java:1270)
[MonoDroid] 	at android.graphics.Canvas.drawBitmap(Canvas.java:1404)
[MonoDroid] 	at android.graphics.drawable.BitmapDrawable.draw(BitmapDrawable.java:544)
[MonoDroid] 	at android.widget.ImageView.onDraw(ImageView.java:1259)
[MonoDroid] 	at android.view.View.draw(View.java:16199)
[MonoDroid] 	at android.view.View.updateDisplayListIfDirty(View.java:15196)
[MonoDroid] 	at android.view.View.draw(View.java:15969)
[MonoDroid] 	at android.view.ViewGroup.drawChild(ViewGroup.java:3612)
[MonoDroid] 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3402)
[MonoDroid] 	at android.view.View.updateDisplayListIfDirty(View.java:15191)
[MonoDroid] 	at android.view.View.draw(View.java:15969)
[MonoDroid] 	at android.view.ViewGroup.drawChild(ViewGroup.java:3612)
[MonoDroid] 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3402)
[MonoDroid] 	at android.view.View.updateDisplayListIfDirty(View.java:15191)
[MonoDroid] 	at android.view.View.draw(View.java:15969)
[MonoDroid] 	at android.view.ViewGroup.drawChild(ViewGroup.java:3612)
[MonoDroid] 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3402)
[MonoDroid] 	at android.view.View.updateDisplayListIfDirty(View.java:15191)
[MonoDroid] 	at android.view.View.draw(View.java:15969)
[MonoDroid] 	at android.view.ViewGroup.drawChild(ViewGroup.java:3612)
[MonoDroid] 	at android.view.View.updateDisplayListIfDirty(View.java:15191)
[MonoDroid] 	at android.view.View.draw(View.java:15969)
[MonoDroid] 	at android.view.ViewGroup.drawChild(ViewGroup.java:3612)
[MonoDroid] 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3402)
[MonoDroid] 	at android.view.View.draw(View.java:16202)
[MonoDroid] 	at android.view.View.updateDisplayListIfDirty(View.java:15196)
[MonoDroid] 	at android.view.View.draw(View.java:15969)
[MonoDroid] 	at android.view.ViewGroup.drawChild(ViewGroup.java:3612)
[MonoDroid] 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3402)
[MonoDroid] 	at android.view.View.draw(View.java:16202)
[MonoDroid] 	at android.view.View.draw(View.java:15969)
[MonoDroid] 	at android.view.ViewGroup.drawChild(ViewGroup.java:3612)
[MonoDroid] 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3402)
[MonoDroid] 	at android.view.View.draw(View.java:16202)
[MonoDroid] 	at android.view.View.updateDisplayListIfDirty(View.java:15196)
[MonoDroid] 	at android.view.View.draw(View.java:15969)
[MonoDroid] 	at android.view.ViewGroup.drawChild(ViewGroup.java:3612)
[MonoDroid] 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3402)
[MonoDroid] 	at android.view.View.updateDisplayListIfDirty(View.java:15191)
[MonoDroid] 	at android.view.View.draw(View.java:15969)
[MonoDroid] 	at android.view.ViewGroup.drawChild(ViewGroup.java:3612)
[MonoDroid] 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3402)
[MonoDroid] 	at android.view.View.draw(View.java:16202)
[MonoDroid] 	at android.widget.HorizontalScrollView.draw(HorizontalScrollView.java:1628)
[MonoDroid] 	at android.view.View.updateDisplayListIfDirty(View.java:15196)
[MonoDroid] 	at android.view.View.draw(View.java:15969)
[MonoDroid] 	at android.view.ViewGroup.drawChild(ViewGroup.java:3612)
[MonoDroid] 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3402)
[MonoDroid] 	at android.view.View.draw(View.java:16202)
[MonoDroid] 	at android.widget.ScrollView.draw(ScrollView.java:1715)
[MonoDroid] 	at md5b60ffeb829f638581ab2bb9b1a7f4f3f.ScrollViewRenderer.n_draw(Native Method)
[MonoDroid] 	at md5b60ffeb829f638581ab2bb9b1a7f4f3f.ScrollViewRenderer.draw(ScrollViewRenderer.java:59)
[MonoDroid] 	at android.view.View.updateDisplayListIfDirty(View.java:15196)
[MonoDroid] 	at android.view.View.draw(View.java:15969)
[MonoDroid] 	at android.view.ViewGroup.drawChild(ViewGroup.java:3612)
[MonoDroid] 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3402)
[MonoDroid] 	at androi	at android.view.View.draw(View.java:16202)
[MonoDroid] 	at android.view.View.updateDisplayListIfDirty(View.java:15196)
[MonoDroid] 	at android.view.View.draw(View.java:15969)
[MonoDroid] 	at android.view.ViewGroup.drawChild(ViewGroup.java:3612)
[MonoDroid] 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3402)
[MonoDroid] 	at android.view.View.updateDisplayListIfDirty(View.java:15191)
[MonoDroid] 	at android.view.View.draw(View.java:15969)
[MonoDroid] 	at android.view.ViewGroup.drawChild(ViewGroup.java:3612)
[MonoDroid] 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3402)
[MonoDroid] 	at android.view.View.updateDisplayListIfDirty(View.java:15191)
[MonoDroid] 	at android.view.View.draw(View.java:15969)
[MonoDroid] 8 I/MonoDroid(19360): 	at android.view.ViewGroup.drawChild(ViewGroup.java:3612)
[MonoDroid] 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3402)
[MonoDroid] 	at android.view.View.draw(View.java:16202)
[MonoDroid] 	at android.view.View.updateDisplayListIfDirty(View.java:15196)
[MonoDroid] 	at android.view.View.draw(View.java:15969)
[MonoDroid] 	at android.view.ViewGroup.drawChild(ViewGroup.java:3612)
[MonoDroid] 	at android.view.View.updateDisplayListIfDirty(View.java:15191)
[MonoDroid] 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3402)
[MonoDroid] 	at android.view.View.draw(View.java:15969)
[MonoDroid] 	at android.view.ViewGroup.drawChild(ViewGroup.java:3612)
[MonoDroid] 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3402)
[MonoDroid] 	at android.view.View.draw(View.java:16202)
[MonoDroid] 	at android.view.View.updateDisplayListIfDirty(View.java:15196)
[MonoDroid] 	at android.view.View.draw(View.java:15969)
[MonoDroid] 	at android.view.ViewGroup.drawChild(ViewGroup.java:3612)
[MonoDroid] 	at android.view.View.updateDisplayListIfDirty(View.java:15191)
[MonoDroid] 	at android.view.View.draw(View.java:15969)
[MonoDroid] 	at android.view.ViewGroup.drawChild(ViewGroup.java:3612)
[MonoDroid] 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3402)
[MonoDroid] 	at android.view.View.updateDisplayListIfDirty(View.java:15191)
[MonoDroid] 	at android.view.View.draw(View.java:15969)
[MonoDroid] 	at android.view.ViewGroup.drawChild(ViewGroup.java:3612)
[MonoDroid] 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3402)
[MonoDroid] 	at android.view.View.updateDisplayListIfDirty(View.java:15191)
[MonoDroid] 	at android.view.View.draw(View.java:15969)
[MonoDroid] 	at android.view.ViewGroup.drawChild(ViewGroup.java:3612)
[MonoDroid] 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3402)
[MonoDroid] 	at android.view.View.updateDisplayListIfDirty(View.java:15191)
[MonoDroid] 	at android.view.View.draw(View.java:15969)
[MonoDroid] 	at android.view.ViewGroup.drawChild(ViewGroup.java:3612)
[MonoDroid] 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3402)
[MonoDroid] 	at android.view.View.draw(View.java:15969)
[MonoDroid] 	at android.view.ViewGroup.drawChild(ViewGroup.java:3612)
[MonoDroid] 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3402)
[MonoDroid] 	at android.view.View.updateDisplayListIfDirty(View.java:15191)
[MonoDroid] 	at android.view.View.draw(View.java:15969)
[MonoDroid] 	at android.view.ViewGroup.drawChild(ViewGroup.java:3612)
[MonoDroid] 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3402)
[MonoDroid] 	at android.view.View.updateDisplayListIfDirty(View.java:15191)
[MonoDroid] 	at android.view.View.draw(View.java:15969)
[MonoDroid] 	at android.view.ViewGroup.drawChild(ViewGroup.java:3612)
[MonoDroid] 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3402)
[MonoDroid] 	at android.view.View.updateDisplayListIfDirty(View.java:15191)
[MonoDroid] 	at android.view.View.draw(View.java:15969)
[MonoDroid] 	at android.view.ViewGroup.drawChild(ViewGroup.java:3612)
[MonoDroid] 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3402)
[MonoDroid] 	at android.view.View.draw(View.java:16202)
[MonoDroid] 	at com.android.internal.policy.PhoneWindow$DecorView.draw(PhoneWindow.java:2690)
[MonoDroid] 	at android.view.View.updateDisplayListIfDirty(View.java:15196)
[MonoDroid] 	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:281)
[MonoDroid] 	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:287)
[MonoDroid] 	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:322)
[MonoDroid] 	at android.view.ViewRootImpl.draw(ViewRootImpl.java:2627)
[MonoDroid] 	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2446)
[MonoDroid] 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2079)
[MonoDroid] 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1119)
[MonoDroid] 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6060)
[MonoDroid] 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
[MonoDroid] 	at android.view.Choreographer.doCallbacks(Choreographer.java:670)
[MonoDroid] 	at android.view.Choreographer.doFrame(Choreographer.java:606)
[MonoDroid] 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
[MonoDroid] 	at android.os.Handler.handleCallback(Handler.java:746)
[MonoDroid] 	at android.os.Handler.dispatchMessage(Handler.java:95)
[MonoDroid] 	at android.os.Looper.loop(Looper.java:148)
[MonoDroid] 	at android.app.ActivityThread.main(ActivityThread.java:5443)
[MonoDroid] 	at java.lang.reflect.Method.invoke(Native Method)
[MonoDroid] 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
[MonoDroid] 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
