### ISSUE TITLE
Xamarin Forms: FFImageLoading caches dead or failed links

### ISSUE THREAD

**Issue by patook** [molinch/FFImageLoading#40] opened 2015-09-24 09:59 UTC
If I try to load 20 images from the same server and one of them doesn't respond (even with .Retry(3,2000)), that dead image gets cached. 

Is there a way to make sure only good images get cached? I am using Xamarin Forms.

**Comment by molinch** [comment] 2015-09-24 18:01
Do you have a custom configuration when you initialize the lib?
Also this issue occurs on iOS, android or both ?

**Comment by patook** [comment] 2015-09-25 04:08
No custom config - this issue occurred for me on iOS, I have not set up Android for this.

I am using the CachedImage class in XF, and initializing the ImageService within the iOS appdelegate

**Comment by molinch** [comment] 2015-09-25 05:28
@patook could you please send some URL that cause this issue?

**Comment by patook** [comment] 2015-09-25 06:02
@molinch Thanks: I suspect the error that happened is that HttpConnection limit was reached. I got a debug message saying that URL was being queued. As I mentioned, I am requesting 24 images simultaneously from the same server.

Also, I can make the change and download your code instead of using nuget but it might be nice if you have an option to never cache empty/zero bytes.

**Comment by molinch** [comment] 2015-09-25 06:22
Still even if you have simultaneous requests it should not do that. I would rather fix that.
Could you share a code sample? If it is private code you can also email me.

**Comment by molinch** [comment] 2015-09-29 16:22
@patook Any news?

**Comment by molinch** [comment] 2015-10-13 05:59
@patook I cannot reproduce so if I don't have news I will close this issue.

**Comment by patook** [comment] 2015-10-13 16:30
Hi Fabien,

 

Sorry I ended up switching to a different image grabbing system since I had to push out the app urgently.

 

The way I had reproed it was by fetching 24 images from the same domain. One of them failed to download (which is fine) but then the empty image was cached.

 

Best

**Comment by molinch** [comment] 2015-10-16 17:37
I don't have this issue and there is no sample to reproduce so I close it.

**Closed** 2015-10-16 17:37 UTC

**Comment by daniel-luberda** [comment] 2015-10-16 21:44
I was trying to test it too. Couldn't reproduce it. So it's safe to close it for now.
