### ISSUE TITLE
Occasionally Images Just Stop Loading

### ISSUE THREAD

**Issue by highplains** [molinch/FFImageLoading#122] opened 2016-01-12 20:00 UTC
After my app has been in use for a while on a device, usually after multiple days. Images appear to just stop loading.

These images should be cached for the most part and network connectivity is not the issue. Not sure why it happens but the screenshot demonstrates what occurs. When this does happen nothing short of killing and restarting the app seems to fix it.

![img_5690](https://cloud.githubusercontent.com/assets/1825076/12275258/838f49e0-b92c-11e5-91a6-1f154b5e834a.PNG)

**Comment by daniel-luberda** [comment] 2016-01-12 20:04
@highplains That's strange. Does it happen only on iOS?

**Comment by highplains** [comment] 2016-01-12 20:32
Feels like it does, but honestly I'm not in the android version enough to give you an answer on that.

**Comment by daniel-luberda** [comment] 2016-01-12 20:33
@highplains I added some more questions to previous post. Could you check it?

**Comment by highplains** [comment] 2016-01-12 20:34
CacheDuration = TimeSpan.FromDays(30);
I never invalidate the cache.
No Exceptions.
Production app, this is occurring in the App Store Release.
I use testflight for beta testing so it would be Release Builds.

**Comment by highplains** [comment] 2016-01-12 20:39
Also the images load fine after restarting the app so shouldn't that mean there is no corruption?

**Comment by molinch** [comment] 2016-01-12 20:42
Do you have exceptions or errors logged?

**Comment by highplains** [comment] 2016-01-12 20:46
No errors at all, I wish there was it would make it easy to find then.

**Comment by daniel-luberda** [comment] 2016-01-12 21:01
@molinch Could it be an out of memory exception?

**Comment by molinch** [comment] 2016-01-12 21:06
Yes that's a possibility 
It's strange that there is nothing in logs though

**Comment by daniel-luberda** [comment] 2016-01-12 21:10
It's a handled exception, so it may only clear the caches and return null every time without any further exceptions.

**Comment by highplains** [comment] 2016-01-12 21:16
interesting. Any thoughts on what i can do to remedy this?

**Comment by molinch** [comment] 2016-01-12 21:21
If there was OOMs there would be at least in the logs:
`Received an OutOfMemoryException we will clear the cache`
or
`Received an OutOfMemoryException`

If it's not the case then we should look into another direction.
Could you post your ImageLoading request?

**Comment by daniel-luberda** [comment] 2016-01-12 21:23
@molinch By default, the logs are only printed to console. They can be not visible when using Xamarin.Insights or something similar without using custom logger initialized in `ImageService.Initialize` for FFImageLoading.

**Comment by highplains** [comment] 2016-01-12 21:30
What do you mean by request? 

All that im doing is 
_image.Source = model.ImageUrl;

OnBindingContextChanged

**Comment by daniel-luberda** [comment] 2016-01-12 21:38
@highplains For the future, you could make a custom logger for FFImageLoading:
 
```C#
    public class CustomMiniLogger: IMiniLogger
    {
        public void Debug(string message)
        {
        }

		public void Error(string errorMessage)
		{
			Insights.Report(ex);
		}

        public void Error(string errorMessage, Exception ex)
        {
			Insights.Report(ex, errorMessage);
        }
    }
```

and force FFImageloading to use it with: 

```C#
ImageService.Initialize(logger: new CustomMiniLogger());
```

in a platform specific project.

**Comment by highplains** [comment] 2016-01-12 21:42
so in iOS for instance i would have this in my FinishedLaunching...

                FFImageLoading.Forms.Touch.CachedImageRenderer.Init();
                FFImageLoading.ImageService.Initialize(logger: new CustomMiniLogger());

?

**Comment by daniel-luberda** [comment] 2016-01-12 21:44
@highplains Yes

**Comment by highplains** [comment] 2016-01-12 21:46
That creates a System.Net.Http dependency and requires Nuget 3.0, let me see if i can pop into Visual Studio and add that package.

**Comment by highplains** [comment] 2016-01-12 21:53
That package fails to install on a iOS project. Have you ever used the custom logger in a forms project before?

**Comment by daniel-luberda** [comment] 2016-01-12 22:03
You don't need to include any nuget. Instead add this as a reference: 
![screen shot 2016-01-12 at 23 02 53](https://cloud.githubusercontent.com/assets/13569983/12278318/bb4c5a0e-b980-11e5-8862-4a6993d81f51.png)

**Comment by highplains** [comment] 2016-01-12 22:05
Maestro! Thank you! Can't believe i missed that. I'm gonna get beta testers on a new version with the logging and ill see what i can turn up.

**Comment by daniel-luberda** [comment] 2016-01-12 22:08
Ok, waiting for some logs :)

**Comment by molinch** [comment] 2016-01-13 06:25
Using Insights for the logger is a great idea :+1:

**Comment by molinch** [comment] 2016-01-17 14:23
Do you have news @highplains ?

**Comment by highplains** [comment] 2016-01-17 16:51
I'm gonna make a repo tomorrow

**Comment by highplains** [comment] 2016-01-17 16:52
Oops diff issue. I haven't heard anything new on this, but have logging in place. We can close this pending logs if needed thanks!

**Comment by molinch** [comment] 2016-01-17 19:24
Thanks for the feedback @highplains 
I agree with you: let's close the issue. If you reproduce it and have more info could you reopen it?

**Closed by molinch** 2016-01-17 19:24 UTC
Labels: more info needed

**Comment by highplains** [comment] 2016-01-26 23:56
I finally got my phone into a state to look around on this problem. Although I am using a custom logger with Insights I don't see, to be getting any reports. Looking at the device console logs I'm seeing a lot of memory warnings which makes me think it does have to do with memory. 

Jan 26 16:51:28 iPhone syncdefaultsd[2149] <Notice>: (Warn ) received memory warning
Jan 26 16:51:29 iPhone com.apple.CDScheduler[26] <Error>: Thermal pressure state: 0 Memory pressure state: 1
Jan 26 16:51:35 iPhone Music[184] <Warning>: Received memory warning.
Jan 26 16:51:38 iPhone MobileMail[1430] <Warning>: Received memory warning.
Jan 26 16:51:39 iPhone InCallService[324] <Warning>: Received memory warning.
Jan 26 16:51:39 iPhone com.apple.CDScheduler[26] <Error>: SysAdmChk: Throttling activity execution. memFlags:0x1 thermalLevel:0x0
Jan 26 16:51:39 iPhone com.apple.CDScheduler[26] <Error>: SysAdmChk: Throttling activity execution. memFlags:0x1 thermalLevel:0x0
Jan 26 16:51:39 iPhone RRiOS[2091] <Warning>: Received memory warning.
Jan 26 16:51:45 iPhone SpringBoard[58] <Warning>: Received memory warning.
Jan 26 16:51:46 iPhone UserEventAgent[26] <Warning>: low memory session log
Jan 26 16:51:46 iPhone UserEventAgent[26] <Warning>: Filtering only beta sessions
Jan 26 16:51:46 iPhone UserEventAgent[26] <Warning>: processing com.rollrandom.rollrandom with 14 events
Jan 26 16:51:46 iPhone UserEventAgent[26] <Warning>: processing com.rollrandom.rollrandom with 21 events
Jan 26 16:51:46 iPhone UserEventAgent[26] <Warning>: Session log: 2 bundles written to /var/mobile/Library/Logs/CrashReporter/log-sessions-2016-01-26-165146.session
Jan 26 16:53:28 iPhone syncdefaultsd[2149] <Notice>: (Note ) marked "com.me.keyvalueservice" topic as "enabled" on <APSConnection: 0x14751cba0>

Any thoughts?

**Comment by daniel-luberda** [comment] 2016-01-27 01:07
It looks like you're hitting out of memory issues. It may not be related to FFImageLoading at all. Some tips regarding FFImageLoading: 

- If you're using events with CachedImage, be sure you're unsubscribing it correctly (`IDisposable`, etc) to be sure `CachedImage` instances are garbage collected correctly.
- Be sure you're using proper downscaled images (less ram usage) with values optimized for a device capacity. 
- Set CachedImage.Source to null when not displayed anymore to allow bitmap recycling. If it's a large image you can call `CachedImage.Invalidate` to remove its instance from cache if you're not going to use it anymore.

**Comment by highplains** [comment] 2016-01-27 01:35
Wouldn't a OOM close/crash the app? My app continues to run in this situation with everything but images working.

**Comment by daniel-luberda** [comment] 2016-01-27 01:41
FFImageLoading worker detects OOM and tries to clean cache first and then if there are still some problems, it can return null bitmaps. I think it's the case.

**Comment by molinch** [comment] 2016-01-27 06:18
I think we could deliver some stats about memory usage.
This way Alan could call the method in his logger to get more info.

**Comment by molinch** [comment] 2016-01-27 06:20
Alan, do you know how long the app was opened before the user started having this issue?

**Comment by highplains** [comment] 2016-01-27 15:52
What I did was create a memory intensive scenario that purposely loaded too
many images. Roughly about 300 images, then played in the app until i
noticed the images stopped loading.
