### ISSUE TITLE
CircleTransformation is not properly drawing the image using Xamarin.Forms 2.0

### ISSUE THREAD

**Issue by davidtavarez** [molinch/FFImageLoading#73] opened 2015-11-21 22:05 UTC
After update to Xamarin.Forms 2.0 the Transformation is not working property.

![simulator screen shot nov 21 2015 5 46 40 pm](https://cloud.githubusercontent.com/assets/337107/11320745/604f1936-907a-11e5-8168-7afe526cb223.png)

Look the left column.

**Comment by daniel-luberda** [comment] 2015-11-22 16:58
On the screenshot you provided CachedImage isn't a square, for a CircleTransformation Image should be a square. Did you try to set WidthRequest and HeightRequest manually?

CircleTransformation could definitely be updated to support those kind of cases though.

**Comment by davidtavarez** [comment] 2015-11-22 17:07
This was working perfectly before. I just update XF to 2.0

**Comment by daniel-luberda** [comment] 2015-11-22 17:08
Xamarin.Forms 2.0 has some new bugs. Could you try to set WidthRequest and HeightRequest manually? It could help me to debug the problem.

**Comment by daniel-luberda** [comment] 2015-11-24 16:16
@davidtavarez Any news?

**Comment by davidtavarez** [comment] 2015-11-24 17:20
I'm changing some logic in my code, I'll post the results :)

**Comment by ThomasKIT** [comment] 2015-11-24 23:58
I can second that error. I already was wondering why ... :-D

Here is my Code, It'll display a circled cached image:
![image](https://cloud.githubusercontent.com/assets/5929104/11384379/80ffe560-930f-11e5-8338-3c21b70aa768.png)

But, as soon as I change the ImageSource, I get exactly the same behaviour as the first screenshot of david depicts it.

**Comment by daniel-luberda** [comment] 2015-11-25 00:32
I'll try to debug that... Is it only on iOS?

**Comment by ThomasKIT** [comment] 2015-11-25 00:44
Alright, so I am not the only one with that bug :-D 
I can second that behaviour. :+1: 

Android & iOS:
If I explicitly set the WidthRequest and HeightRequest, I'll get the same semi-circle with those edges.
If I surround it with a custom control and inherit the bounds, everything seems to be fine.

Only on iOS:
Unless ... the Image Source gets changed, this will even turn that custom control containing the cached image into the weird circle.


Although what seems to be working all the time is

Here are my Code snippets.

User Control:
![image](https://cloud.githubusercontent.com/assets/5929104/11384961/b7900056-9314-11e5-90a0-36850d5eec35.png)


Inside a ListView Cell evertyhing works fine:
![image](https://cloud.githubusercontent.com/assets/5929104/11384983/0d8de310-9315-11e5-8dd9-a43e45481e34.png)

**Comment by daniel-luberda** [comment] 2015-11-25 01:34
Will try to debug it soon when I'll have some time. 

*Oh Xamarin... dear xamarin.... where to start?* :P

**Comment by daniel-luberda** [comment] 2015-11-25 01:45
> There is a new experimental layout optimization in this release of Xamarin.Forms. The optimization is complex and currently only impacts layout updates. Effectively the optimization serves to block InvalidateMeasure call chains. To get the best possible performance follow these performance guidelines:

> Leave the View.VerticalOptions and View.HorizontalOptions alone as much as possible. The default value of Fill or FillAndExpand allows for the best layout optimization.
When using a StackLayout, make sure to have only one child set to Expand.
Avoid RelativeLayout when possible.
When using Grid, avoid Auto rows/columns if possible. Fixed row/cols are best. Stars are equally good if parent tree follows guidelines.
When using AbsoluteLayout, avoid using AutoSize if possible.
When using Labels, set the LineBreakMode to NoWrap whenever possible.
This optimization may impact the layout of your app. If you experience any differences at all, please report them as bugs.

**Comment by daniel-luberda** [comment] 2015-11-25 03:35
@davidtavarez @ThomasKIT 
Could you try this: https://github.com/molinch/FFImageLoading/commit/ebe66d53de2fce56b3e1108ba3987edfd8e23e94 ? Can't test it now.

**Comment by ThomasKIT** [comment] 2015-11-25 07:39
Haha nice optimizations xamarin :-D

Not using the HorizontalOptions is kind of making it worse as it stretches the image across the full length.

But what seems to work is explicitly setting MinimumHeightRequest and MinimumWidthRequest.
This seems to fix it.

I will have to try it on iOS, but I can't right now.

**Comment by daniel-luberda** [comment] 2015-11-25 12:22
@ThomasKIT What about my fix? Did it help? Link: https://github.com/molinch/FFImageLoading/commit/ebe66d53de2fce56b3e1108ba3987edfd8e23e94

**Comment by daniel-luberda** [comment] 2015-11-30 12:26
Any news?

**Comment by davidtavarez** [comment] 2015-11-30 15:06
I updated the package... same results.
![simulator screen shot nov 30 2015 11 01 26 am](https://cloud.githubusercontent.com/assets/337107/11475182/60e60240-9752-11e5-9027-975b14190bce.png)

**Comment by molinch** [comment] 2015-11-30 15:10
the package was not updated so far. The fix is in git only. So you didn't tried using git sources isn't it?

But packages will very soon be changed.

**Comment by davidtavarez** [comment] 2015-11-30 15:11
@molinch no, I can't compile the source. I tried once.

**Comment by daniel-luberda** [comment] 2015-12-02 08:03
### FFImageLoading v2.0.0-alpha1 nuget released
https://www.nuget.org/packages/Xamarin.FFImageLoading.Forms/2.0.0-alpha1
https://www.nuget.org/packages/Xamarin.FFImageLoading.Transformations/2.0.0-alpha1

Can you try it?

**Comment by davidtavarez** [comment] 2015-12-02 15:14
Yes, right now.

**Comment by davidtavarez** [comment] 2015-12-02 15:45
Same results.
![simulator screen shot dec 2 2015 11 43 04 am](https://cloud.githubusercontent.com/assets/337107/11535357/e2b78472-98e9-11e5-9399-f3abfee74a73.png)

I'll try changing the size... now, I'm just testing the package, I'm not changing the code that was working before.

**Comment by davidtavarez** [comment] 2015-12-02 15:57
Yes... I changed HeightRequest and WidthRequest to 0 (zero) and the result is the same.
![screen shot 2015-12-02 at 11 56 40 am](https://cloud.githubusercontent.com/assets/337107/11535794/d4968fee-98eb-11e5-94fa-42a621665d51.png)
![screen shot 2015-12-02 at 11 55 15 am](https://cloud.githubusercontent.com/assets/337107/11535796/d8a2f136-98eb-11e5-8532-4ce17b94db76.png)

**Comment by davidtavarez** [comment] 2015-12-02 15:59
Something is really wrong with XF2.0

**Comment by davidtavarez** [comment] 2015-12-02 16:04
Even if I change to Image the result is the same.

**Comment by highplains** [comment] 2015-12-02 16:14
If that's the case can you open a bugzilla with xamarin? I'd like to follow that

**Comment by davidtavarez** [comment] 2015-12-02 16:21
@highplains yes I did

https://bugzilla.xamarin.com/show_bug.cgi?id=36470

**Comment by molinch** [comment] 2015-12-02 16:56
Wow that's a nasty regression!

**Comment by daniel-luberda** [comment] 2015-12-02 17:38
If it's a Xamarin.Forms bug - we could close the issue now. Thanks for the info!

**Closed by daniel-luberda** 2015-12-02 17:38 UTC
Labels: more info needed

**Comment by vhugogarcia** [comment] 2017-03-15 16:45
Hello @daniel-luberda 

I'm having the same issue and I'm using Xamarin.Forms 2.3.3.180.

This is the code I'm using:
`<ffimageloading:CachedImage x:Name="Image" HorizontalOptions="Center" VerticalOptions="Center" DownsampleToViewSize="true" Source="{Binding Photo}" Aspect="AspectFill" Grid.Row="0" Grid.Column="0" Grid.RowSpan="2" Margin="0,0,10,5"
							HeightRequest="150" WidthRequest="150">
	<ffimageloading:CachedImage.Transformations>
		<fftransformations:CircleTransformation />
	</ffimageloading:CachedImage.Transformations>
</ffimageloading:CachedImage>`

Any idea how to fix it?

Thanks in advance
