### ISSUE TITLE
Occasionally Wrong Image is Cached and Displayed.

### ISSUE THREAD

**Issue by highplains** [molinch/FFImageLoading#140] opened 2016-02-03 17:01 UTC
I've noticed that sometimes the wrong image gets cached and displayed.

Example.

Notice the image for "Susie O."
![screen shot 2016-02-03 at 9 57 00 am](https://cloud.githubusercontent.com/assets/1825076/12789776/7c0ce34e-ca5c-11e5-937e-7bb7402df541.png)

In the database on the device the image url is: http://d3jwlazd4lxjto.cloudfront.net/4435D05D1CEE3E9A011CD841CBBE86F8   which is the correct image.

Even after restarting the app this image still shows for this users profile.

If i look at the cached file saved by the lib. MD5:51774df1cd016d95ea144801d492601b of the above link i can see the wrong image in the disk cache.

![screen shot 2016-02-03 at 10 00 28 am](https://cloud.githubusercontent.com/assets/1825076/12789908/fe7d7ec4-ca5c-11e5-8949-5ee4283e584e.png)

**Comment by molinch** [comment] 2016-02-03 17:52
Do you use a specific cache key?

**Comment by highplains** [comment] 2016-02-03 18:00
I use defaults, so no.

**Comment by molinch** [comment] 2016-02-03 18:12
The issue is on iOS or Android?

**Comment by molinch** [comment] 2016-02-03 18:48
Other question: I guess you use latest stable nugets?

**Comment by highplains** [comment] 2016-02-03 18:50
I've only tested on ios

**Comment by highplains** [comment] 2016-02-03 18:51
The problem occurs in latest stable and alphas

**Comment by molinch** [comment] 2016-02-03 19:04
Thanks for the feedback I am investigating.

I don't know if that's possible for you but if you build the lib from sources, in debug, and run your app with it in debug then valuable logs will be in the console.
If you can do so could you attach them here?

**Comment by highplains** [comment] 2016-02-03 19:56
2016-02-03 12:55:37.636 RRiOS[23298:8594846] Generating/retrieving image: http://d3jwlazd4lxjto.cloudfront.net/4435D05D1CEE3E9A011CD841CBBE86F8;120x0
Generating/retrieving image: http://d3jwlazd4lxjto.cloudfront.net/4435D05D1CEE3E9A011CD841CBBE86F8;120x0

That is the log entry for the relative image.

**Comment by highplains** [comment] 2016-02-03 20:20
Seeing it for other profiles as well. In this image "Rob S" is showing the correct image while "Vidal L." is showing the wrong image.

![screen shot 2016-02-03 at 1 16 24 pm](https://cloud.githubusercontent.com/assets/1825076/12795749/b7606be8-ca78-11e5-9de3-6fd1f4178f89.png)

Rob S: http://d3jwlazd4lxjto.cloudfront.net/EEB5D7BF24B6F139B6E6F179E9085473;120x0
Vidal L: http://d3jwlazd4lxjto.cloudfront.net/C9FA969DF36F7902EB96A12D5C4409A1;120x0

Logs.
2016-02-03 13:15:37.021 RRiOS[23375:8742556] Canceled image generation for http://d3jwlazd4lxjto.cloudfront.net/20A57C470E8D26077F3AC5566140EC14;120x0
Canceled image generation for http://d3jwlazd4lxjto.cloudfront.net/20A57C470E8D26077F3AC5566140EC14;120x0
2016-02-03 13:15:37.023 RRiOS[23375:8743365] Generating/retrieving image: http://d3jwlazd4lxjto.cloudfront.net/4435D05D1CEE3E9A011CD841CBBE86F8;120x0
Generating/retrieving image: http://d3jwlazd4lxjto.cloudfront.net/4435D05D1CEE3E9A011CD841CBBE86F8;120x0
Thread finished: <Thread Pool> #15
Thread finished: <Thread Pool> #4
2016-02-03 13:15:42.400 RRiOS[23375:8742556] Canceled image generation for http://d3jwlazd4lxjto.cloudfront.net/C43B54C61E8884D3DAACB689549D8BA3;120x0
Canceled image generation for http://d3jwlazd4lxjto.cloudfront.net/C43B54C61E8884D3DAACB689549D8BA3;120x0
Thread started: <Thread Pool> #18
2016-02-03 13:15:42.402 RRiOS[23375:8743517] Generating/retrieving image: http://d3jwlazd4lxjto.cloudfront.net/EEB5D7BF24B6F139B6E6F179E9085473;120x0
Generating/retrieving image: http://d3jwlazd4lxjto.cloudfront.net/EEB5D7BF24B6F139B6E6F179E9085473;120x0
Thread finished: <Thread Pool> #5
Thread finished: <Thread Pool> #6
2016-02-03 13:15:49.660 RRiOS[23375:8743295] Generating/retrieving image: http://d3jwlazd4lxjto.cloudfront.net/C9FA969DF36F7902EB96A12D5C4409A1;120x0
Generating/retrieving image: http://d3jwlazd4lxjto.cloudfront.net/C9FA969DF36F7902EB96A12D5C4409A1;120x0
2016-02-03 13:15:53.979 RRiOS[23375:8742556] Canceled image generation for http://d3jwlazd4lxjto.cloudfront.net/98C2F6221EC14EA0B429F2093E7A7B99;120x0
Canceled image generation for http://d3jwlazd4lxjto.cloudfront.net/98C2F6221EC14EA0B429F2093E7A7B99;120x0

**Comment by molinch** [comment] 2016-02-04 06:01
Thanks it will definitely help for debugging.
Do you use XF recycling strategy?

**Comment by highplains** [comment] 2016-02-04 14:33
No I use uneven rows a lot so RetainElement

**Comment by daniel-luberda** [comment] 2016-02-04 16:06
The important one is: 

>Even after restarting the app this image still shows for this users profile.

My types: 

- Corrupted journal file. Clearing image cache should help. Did you try that?
- Concurrency error when saving journal entry. (we use locks so I don't think it's the case)

**Comment by highplains** [comment] 2016-02-04 16:31
I'm pretty sure clearing the cache will work as well, but that doesn't help my users that might experience this. More interested in how it occurs in the first place.

**Comment by daniel-luberda** [comment] 2016-02-04 16:34
@highplains Yes, we definitely need to track it down. Did you ever use methods for clearing disk cache in your app? There was a bug in previous version which could corrupt journal file: https://github.com/molinch/FFImageLoading/commit/91ba594516694935b8aed4d0cdf0ae4bcdbf5593

**Comment by highplains** [comment] 2016-02-04 16:35
No I've never used any invalidation routines before. Never needed to.

**Comment by daniel-luberda** [comment] 2016-02-04 16:40
Is it possible that you could mail me `.journal` file so I could analyze it if it's corrupted and if it contains correct entries?

**Comment by highplains** [comment] 2016-02-04 16:45
sent

**Comment by daniel-luberda** [comment] 2016-02-04 18:42
@highplains Thanks for the files. Some more information: 

### Example1
c 8e090fa1e3842e825e64cd49a0ac8071 635901144972886480 2592000000
c 51774df1cd016d95ea144801d492601b 635901144979156220 2592000000
m 51774df1cd016d95ea144801d492601b 635901144980165350 2592000000

http://d3jwlazd4lxjto.cloudfront.net/4435D05D1CEE3E9A011CD841CBBE86F8 (file: 51774df1cd016d95ea144801d492601b) was cached as http://d3jwlazd4lxjto.cloudfront.net/7C30B05FFD485DE46E7190FD40E2BB6C (file: 8e090fa1e3842e825e64cd49a0ac8071) - wrong file was saved as 51774df1cd016d95ea144801d492601b

### Example2
c 5388249d537a15f08b0abd010f8089f2 635901144975608530 2592000000
m 5388249d537a15f08b0abd010f8089f2 635901144978257070 2592000000
c fccb4ffe966183ebbfa2223fd0ac1d84 635901146060143760 2592000000

http://d3jwlazd4lxjto.cloudfront.net/C9FA969DF36F7902EB96A12D5C4409A1 (file: 5388249d537a15f08b0abd010f8089f2) was cached as http://d3jwlazd4lxjto.cloudfront.net/EEB5D7BF24B6F139B6E6F179E9085473 (file: fccb4ffe966183ebbfa2223fd0ac1d84) - wrong file was saved as 5388249d537a15f08b0abd010f8089f2

**Comment by molinch** [comment] 2016-02-05 06:54
Thanks for the debugging Daniel. That could definitely explain it.

**Comment by molinch** [comment] 2016-02-07 13:53
Currently I still didn't managed to repro this.
@highplains is it possible to email me a repro sample?

**Comment by highplains** [comment] 2016-02-09 16:33
I don't know the sequence that causes the issue it would be hard for me to create a repo as well.

**Comment by ahohns** [comment] 2016-02-10 03:51
For what it's worth I've seen this too and it's very infrequent and random - I mentioned it in another issue but never created a separate issue as I haven't seen it happen for a while and put it down to something being fixed with the more recent versions.

**Comment by teunhoogendoorn** [comment] 2016-02-25 14:39
I've also seen this happening. In a list of images sometimes a previous loaded image is used instead of the correct image.

**Comment by molinch** [comment] 2016-02-25 15:39
Please note that we consider this issue as a critical one. Therefore for now I have not been able to repro it.

Could be great if any of you was able to deliver some sample where we know we can face this issue.
Even if we hit it after 10mn or rarely, we could heavily play with the sample, until we get it.

**Comment by highplains** [comment] 2016-02-25 15:42
I'm not sure if its relevant but I see this occur in the iOS simulator much
more then my production app. 9:1

**Comment by teunhoogendoorn** [comment] 2016-02-25 15:45
Indeed, mostly seen on iOS simulator.

**Comment by molinch** [comment] 2016-02-27 08:58
@daniel-luberda  I retried to update our sample ListExampleViewModel, I updated this method:
```c#
ObservableCollection<ListExampleItem> GenerateSampleData()
		{
			var images = Enumerable.Range(0, 2000)
				.Select(i => new ListExampleItem()
				{
					ImageUrl = "https://unsplash.it/1000/1000?image=" + i,
					FileName = string.Format("image{0}.jpeg", i),
				});

			var list = new ObservableCollection<ListExampleItem>(images);
			return list;
		}
```

So as you can see I know have tons of pictures of a decent size.
Therefore I'm still unable to reproduce.

**Comment by coonmoo** [comment] 2016-02-29 11:20
I see this also in my android app.
But it's hard to reproduce, because it only happens sometimes.

I does not seem to relate with the number of pictures in the list. I've seen this issue appearing with only 10 cells loaded and only 3 images displayed.

**Comment by molinch** [comment] 2016-03-02 07:38
@daniel-luberda I think we could rewrite a much simpler cache system similar to: https://github.com/JimBobSquarePants/ImageProcessor/blob/master/src/ImageProcessor.Web/Caching/DiskCache.cs

This way we would avoid having a journal file.

**Comment by molinch** [comment] 2016-03-04 10:56
There is now a branch with a different disk cache implementation: https://github.com/molinch/FFImageLoading/tree/simple-diskcache

Basically there is no more journal file.
It would be super awesome if you could play with it and tell me if you still get the issue.

**Comment by molinch** [comment] 2016-03-09 17:48
There is now an alpha nuget that includes these changes: https://www.nuget.org/packages/Xamarin.FFImageLoading.Forms/2.1.0-alpha1

Could you tell us if it fixes the issue? @highplains @ahohns @coonmoo @teunhoogendoorn

**Comment by daniel-luberda** [comment] 2016-04-18 19:24
FFImageLoading 2.1 should eliminate this issue, as new `DiskCache` implementation doesn't use journal file anymore (it bases on filenames). I'll close this one, feel free to reopen it if there are some new details.

**Closed by daniel-luberda** 2016-04-18 19:24 UTC
Labels: more info needed

**Comment by molinch** [comment] 2016-05-17 15:35
@coonmoo Do you have any ImageService.Instance.Initialize() specificities? or anything special that you would be doing?

Disk cache implementation changed, and other fixes have been added. Does it happen on device only, or in simulator as well?

**Comment by coonmoo** [comment] 2016-05-17 16:04
@molinch 

I call the initialize:
 ImageService.Instance.Initialize(new FFImageLoading.Config.Configuration { HttpClient = new HttpClient(new NativeMessageHandler()), Logger = new MySimpleLogger() });

NativeMessageHandler is from ModernHttpClient package.

Otherwise I'm not doing anything special (just using the CachedImageRenderer).

Was only able to see it on my devices yet.

I use the unmodified Nuget packages and did not modify anything.

Thanks in advance!

**Comment by coonmoo** [comment] 2016-05-19 11:13
Tried with FFImageLoading 2.1.0 and could not reproduce this issue anymore.
